<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-07-31
 * Time: 18:40
 */

namespace xlauth\server;


class baiduServer extends authServer
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setAppPlatform('baidu');
    }

    public function setCode($code){
        if (empty($code)){
            throw new \Exception('bdcode not be empty');
        }

        $this->setParams(['bdcode' => $code]);
        return $this;
    }

}