<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-07-25
 * Time: 14:02
 */

namespace xlauth\server;


class oppoServer extends authServer
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setAppPlatform('oppo');
    }

    public function setToken($token)
    {
        if (empty($token))
        {
            throw new \Exception('token not be empty');
        }

        $this->setParams(['token' => $token]);
        return $this;
    }
}