<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-07-22
 * Time: 11:51
 */

namespace xlauth\server;


class qttServer extends authServer
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setAppPlatform('qtt');
    }

    public function setTicket($ticket){
        if (empty($ticket)){
            throw new \Exception('ticket is not be empty');
        }
        $this->setParams(['ticket' => $ticket]);
        return $this;
    }

    public function setPlatform($platform = 'qtt'){
        $this->setParams(['platform' => $platform]);
        return $this;
    }

}