<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-07-31
 * Time: 18:44
 */

namespace xlauth\server;


class sqqServer extends authServer
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setAppPlatform('sqq');
    }

    public function setCode($code){
        if (empty($code)){
            throw new \Exception('sqqCode not be empty');
        }

        $this->setParams(['sqqCode' => $code]);
        return $this;
    }

}