<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-07-22
 * Time: 16:30
 */

namespace xlauth\server;


class testServer extends authServer
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setAppPlatform('test');
    }

    public function setSessionKey($sessionKey){
        $this->setParams(['sessionKey' => $sessionKey]);
        return $this;
    }

}