<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-07-22
 * Time: 15:04
 */

namespace xlauth\server;


class weixinServer extends authServer
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setAppPlatform('weixin');
    }

    public function setCode($code){
        if (empty($code)){
            throw new \Exception('code not be empty');
        }
        $this->setParams(['wxCode' => $code]);
        return $this;
    }

}